### PR TITLE
Migrate to 3.10 compatible abc usage.

### PR DESCRIPTION
**Pull request by novafacing**
This is a one-line fix. Python 3.10 has [deprecated](https://github.com/python/cpython/commit/c47c78b878ff617164b2b94ff711a6103e781753#diff-c92f871cb9b4aa1583c89f82cd416d58a5d70fff41faf41e45dedf775dbe7713) using direct `abc` imports from `collections`.

### CODE REVIEW

**Comment by novafacing** [comment]
The file failing linting isn't touched by this, but I'm happy to submit another PR that fixes that.

**Comment by disconnect3d** [comment]
Hey,

If we accept this PR, we will break Pwndbg for anyone using GDB with Python <3.10.

Honestly, I am disappointed that Python made the effort to deprecate it but introduced an alternative only in 3.10 when the thing got removed? I may be wrong, but it seems so since the proposed change does not work in 3.9:

```
dc@dc:~$ sudo docker run --rm -it python:3.9 python -c 'import collections; print(collections.abc.Hashable)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/collections/__init__.py", line 68, in __getattr__
    raise AttributeError(f'module {__name__!r} has no attribute {name!r}')
AttributeError: module 'collections' has no attribute 'abc'
dc@dc:~$ sudo docker run --rm -it python:3.9 python -c 'import collections; print(collections.Hashable)'
<string>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
<class 'collections.abc.Hashable'>
```

Anyway, I can't accept this change in its current form. Can you make something like:
```python
try:
    # Python >= 3.10
    from collections.abc import Hashable
except ImportError:
    # Python < 3.10
    from collections import Hashable
```

and just use `Hashable` later on?

**Comment by novafacing** [comment]
Interesting, I didn't realize this would break backward compatibility. I'll rework this!

**Comment by novafacing** [comment]
😓 linter ran....sorry about that, I'm not a regular FOSS contributor yet and I'm working on my setup for it!

Should be good now, thanks for the correction!

**Comment by disconnect3d** [comment]
Don't worry about linter, I'll fix it in next PR.
