### ISSUE TITLE
[Bug] pwndbg shows incorrect stack context

### ISSUE THREAD

**Issue by bruce30262** [pwndbg/pwndbg#460]
### Environment
* Ubuntu Linux 16.04 64 bit
* latest version of pwndbg (`1.0.0 build: 824dd96`) (edit: add pwndbg version)

--------------------------

### Details
In some binaries, pwndbg will show the incorrect stack context, for example (sorry for not providing the testing binary, it requires a lot of settings to run this binary and the VM is pretty large) :  
![1](https://user-images.githubusercontent.com/4478350/39750107-f58848c0-52e6-11e8-8759-8629cb40e315.PNG)

I've print out the value of `pwndbg.regs.sp`, and found that it did not match the value of the current esp.  
I couldn't find where pwndbg update the value of `pwndbg.regs.sp` though, so I have no idea where the bug exist.  
 
Strangely, if we modify the value of a register, pwndbg will update the `pwndbg.regs.sp` to the correct value, thus showing the correct stack context:  
![2](https://user-images.githubusercontent.com/4478350/39750278-6d7ba110-52e7-11e8-8a7a-193f10bea6c8.PNG)

--------------------------  

This happened several times, both in x86/x64 architecture. It usually happened while I was debugging a large/complicated binary. The example above was an x86 binary, which is a [libFuzzer](https://llvm.org/docs/LibFuzzer.html) compiled with [ASAN](https://github.com/google/sanitizers/wiki/AddressSanitizer) enabled.  It also happened while I was debugging an x64 version of [SpiderMonkey](https://developer.mozilla.org/zh-TW/docs/Mozilla/Projects/SpiderMonkey).  

I think the way to fix this issue is to update all the registers before showing the context?

**Comment by disconnect3d** [comment]
Hey, thanks for reporting the bug!

It would be good to be able to reproduce it somehow :/. Any chance to work this out together using a TeamViewer or other screen sharing? If so, ping me at freenode irc (same nick).

Maybe it is due to caching something that shouldn't be cached. Could you check if problem exists after disabling cache? This can be done by:
```
pwndbg> python import pwndbg; pwndbg.memoize.memoize.caching = False
```

> latest version of pwndbg

Is it latest `dev` branch? Its best to show the result of `version` command.

> I think the way to fix this issue is to update all the registers before showing the context?

I believe this is what we do already. I think this is the code that is executed when you get register value (e.g. `pwndbg.regs.sp`):
https://github.com/pwndbg/pwndbg/blob/824dd9645cd06cbb5b63f208ee2604cb8ef28b4a/pwndbg/regs.py#L269-L284

PS: Did you change some theme settings? Mind sharing it to others on https://github.com/pwndbg/pwndbg-themes ? :D (if its not @anthraxx's theme ;P).

**Comment by bruce30262** [comment]
Hello @disconnect3d , 

> Any chance to work this out together using a TeamViewer or other screen sharing?  
  
Due to our company policy I'm afraid I can't do that :(  

>Could you check if problem exists after disabling cache?   

**Disabling the cache actually fixes the issue ! But this slows pwndbg down (  a lot !  )**

> Is it latest `dev` branch?  

Yes

>  Its best to show the result of version command.

Here it is:
```
pwndbg> version
Gdb:      GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Python:   3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
Pwndbg:   1.0.0 build: 824dd96
Capstone: 4.0.1024
Unicorn:  1.0.1
```

> Did you change some theme settings? Mind sharing it to others on https://github.com/pwndbg/pwndbg-themes ? :D

Here's my color-theme setting ( from [here](https://github.com/bruce30262/CTF/blob/408406a2ad90c406910359f5d80c77f71a8e42d1/debugger/.gdbinit_pwndbg#L19-L27) ):  
```
# customize color-theme
set banner-color cyan,bold
set context-register-changed-color red,bold
set context-register-color green
set disasm-branch-color yellow
set memory-data-color blue
set memory-heap-color purple,bold
set memory-rodata-color green
set memory-stack-color purple
```
Feel free to copy that and push it to https://github.com/pwndbg/pwndbg-themes :)  
( I'm too lazy to do that :P  )  

Since now we know it's a caching problem, I'll keep tracing the caching part  and see what I can do to fix this issue .

**Comment by bruce30262** [comment]
@disconnect3d I've been debugging for a while, and found that this issue is related to **multi-thread** problem.

-----------------------------
testing binary ( arch : x64 ): 
![test_thread](https://user-images.githubusercontent.com/4478350/39852986-2f197bec-5452-11e8-9d89-4f38be38d338.jpg)

source code: 
```c

/* gcc -o t t.c -lpthread*/

#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>

#define NUM_THREADS 2

void *thr_func1() {
    printf("thr_func1\n");
    int ooo=100000000;
    /* in gdb, press ctrl-c while doing the following operation */
    while(ooo--);
    pthread_exit(NULL);
}

void *thr_func2() {
    printf("thr_func2\n");
    int ooo=100000000;
    /* in gdb, press ctrl-c while doing the following operation */
    while(ooo--);
    pthread_exit(NULL);
}

int main(int argc, char **argv) {
    pthread_t thr[NUM_THREADS];
    int i, rc;

    for (i = 0; i < NUM_THREADS; ++i) {
        if (i == 0)
        {
            if ((rc = pthread_create(&thr[i], NULL, thr_func1, NULL))) {
                fprintf(stderr, "error: pthread_create, rc: %d\n", rc);
                return -1;
            }
        }
        else
        {
            if ((rc = pthread_create(&thr[i], NULL, thr_func2, NULL))) {
                fprintf(stderr, "error: pthread_create, rc: %d\n", rc);
                return -1;
            }
        }
    }
    for (i = 0; i < NUM_THREADS; ++i) {
        pthread_join(thr[i], NULL);
    }

    return 0;
}


``` 

While doing the `while(ooo--);` operation, I stopped pwndbg ( ctrl-c ) and take a look at the stack frame of each thread:  

```
pwndbg> info thread
  Id   Target Id         Frame
* 1    Thread 0x7ffff7fe6700 (LWP 13529) "t" 0x00007ffff7bc298d in pthread_join (threadid=140737345681152, thread_return=0x0) at pthread_join.c:90
  2    Thread 0x7ffff77ef700 (LWP 13533) "t" 0x00000000004007f0 in thr_func1 ()
  3    Thread 0x7ffff6fee700 (LWP 13534) "t" 0x0000000000400824 in thr_func2 ()

```
In thread 1, I check the value of `pwndbg.regs.rsp` & `pwndbg.regs.sp`:

![sss](https://user-images.githubusercontent.com/4478350/39853068-94a70f06-5452-11e8-8f21-6706fc4713bd.PNG)

You can see that they aren't the same value.   
`pwndbg.regs.rsp` always point to the current thread's stack address, but `pwndbg.regs.sp` seems to point to the **newest** thread stack address.  

If we switch to thread 3 and check the value of those regs, we'll see that they become the same value:  

![s2](https://user-images.githubusercontent.com/4478350/39853172-2548f95c-5453-11e8-81d6-f531c5764c49.PNG)

----------------------------------------

I haven't check the code so I don't know how pwndbg handle the multi-thread situation.  
To fix this issue, we'll have to make sure that `pwndbg.regs.sp` is always point to the current thread's stack's top address.

**Comment by disconnect3d** [comment]
Thanks a lot for debugging this. The problem probably comes from the fact on how we fetch registers. From regs.py :
```python
@pwndbg.proc.OnlyWhenRunning
def gdb77_get_register(name):
    return gdb.parse_and_eval('$' + name)

@pwndbg.proc.OnlyWhenRunning
def gdb79_get_register(name):
    return gdb.newest_frame().read_register(name)
```

I guess that we have to either use only the old way (parse and eval) or find out if GDB API has something for retrieving frame from current thread and not just 'newest' (I can't see it right now as I am writing from my phone :p).

**Comment by disconnect3d** [comment]
Hm or it probably comes from the fact we cache registers not to fetch them multiple times. We do invalidate the cache on a stop event, we probably should also check if there is some thread changed event OR we could make the thread id a cache key (not sure how to do that atm tho).

**Comment by zachriggle** [comment]
I was expecting caching to be the issue. I don’t think GDB has a built-in
event for detecting thread swaps — I think we can check every time the
prompt shows?

We’ll likely need another cache / event for threading. I’m honestly sad /
surprised that switching threads doesn’t issue a stop event.

**Comment by bruce30262** [comment]
> I think we can check every time the prompt shows?  

Sounds good. `events.before_prompt` should do the trick.

**Comment by disconnect3d** [comment]
Should be fixed by https://github.com/pwndbg/pwndbg/pull/463.

Thanks a lot for reporting this and for help in finding out what is the issue :1st_place_medal:.

If we ever meet in real life, don't forget to ask for a :beer: :).

**Comment by zachriggle** [comment]
We may want to add the register_changed event for this too.

Also, before_prompt (and others) may break older GDB versions.

Does this still work with Ubuntu 16.04?

**Comment by disconnect3d** [comment]
@zachriggle Good question. I forgot to check it out on older GDBs.

And so... not really:
```
pwndbg> pi
In : import gdb
In : print(dir(gdb.events))
['__doc__', '__name__', '__package__', 'cont', 'exited', 'new_objfile', 'start', 'stop']
In : 
pwndbg> version
Gdb:      GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Python:   2.7.9 (default, Jun 29 2016, 13:11:10)  [GCC 4.9.2]
Pwndbg:   1.0.0 build: 1a5e134
Capstone: 4.0.1024
Unicorn:  1.0.0
```

But it should be fine to reset the prompt cache inside prompt hook for older GDBs. Patch incomming.

**Comment by bruce30262** [comment]
@disconnect3d @zachriggle  bad news, this doesn't work on Ubuntu 16.04 :(  

```
# bruce30262 @ ubuntu in ~/test [19:03:00]
$ cat /etc/issue
Ubuntu 16.04.4 LTS \n \l


# bruce30262 @ ubuntu in ~/test [19:03:03]
$ pgdb -q
Traceback (most recent call last):
  File "~/pwndbg/gdbinit.py", line 36, in <module>
    import pwndbg # isort:skip
  File "/home/bruce30262/pwndbg/pwndbg/__init__.py", line 12, in <module>
    import pwndbg.android
  File "/home/bruce30262/pwndbg/pwndbg/android.py", line 10, in <module>
    import pwndbg.color.message as message
  File "/home/bruce30262/pwndbg/pwndbg/color/__init__.py", line 11, in <module>
    import pwndbg.memoize
  File "/home/bruce30262/pwndbg/pwndbg/memoize.py", line 17, in <module>
    import pwndbg.events
  File "/home/bruce30262/pwndbg/pwndbg/events.py", line 75, in <module>
    gdb.events.before_prompt: []
AttributeError: module 'gdb.events' has no attribute 'before_prompt'  <--- oh no !
/home/bruce30262/.gdbinit:11: Error in sourced command file:
Invalid command to alias to: distance
(gdb)
```  

Also, although this works on Ubuntu 17.10 & Ubuntu 18.04, It still have some bugs.
For example, there are 3 threads, and I'm at thread 1.  
Now I switch to thread 2 by entering `thread 2`, pwndbg will switch to thread 2 but shows thread 3 ( the newest thread's ) stack context:  
<img width="447" alt="default" src="https://user-images.githubusercontent.com/4478350/39952695-3f8f40d2-55cf-11e8-9406-e782f6a0d795.PNG">  

Even worse, now no matter what thread I switch to , pwndbg will always shows the newest thread's stack context ( means that `pwndbg.regs.sp` always point to newest thread's sp ).  
However, if we step/next the gdb, pwndbg will update `pwndbg.regs.sp` to the current thread's sp and shows the correct stack context.  

Like @zachriggle said, we might want to add a register_changed event and keep updating the value of `pwndbg.regs.sp` to the current thread's stack pointer.  
Or, we can check the value of `pwndbg.regs.sp` before the prompt, see if it is the same value of the current thread's sp.

**Comment by zachriggle** [comment]
Register_changed is also not in 7.7 IIRC.

We should be able to get the “same” thing by using our prompt_hook routine
to trigger the event.

**Comment by disconnect3d** [comment]
Trying to make it work on https://github.com/disconnect3d/pwndbg/tree/fix-before-prompt-on-old-gdb
But it seems it caches regs too much atm

**Comment by disconnect3d** [comment]
@bruce30262 I have merged https://github.com/pwndbg/pwndbg/pull/464 which seems to work fine for me. Could you check it out?

**Comment by bruce30262** [comment]
@disconnect3d  tested on Ubuntu 16.04 & 18.04 with the test_thread binary, both of them work really well ! ( Haven't test on those libFuzzer binary though, have to wait until Monday , but I think we're good )

**Comment by disconnect3d** [comment]
@bruce30262 Thanks :100: !

Will close it for now. Feel free to reopen if this happens again.

**Comment by zachriggle** [comment]
Thanks for all the work guys! ❤️
